### ISSUE TITLE
Suggestion for page /content/lessons/screen_recording/screen_recording.html

### ISSUE THREAD

**Issue by PeterBetlem** [UNISvalbard/AG222#2]
Add information on Da Vinci resolve: Free movie editing software used in the big bizz

https://www.blackmagicdesign.com/products/davinciresolve

And add information on Blender (for advanced users):
https://www.blender.org/

**Comment by nilrodes** [comment]
Working on it.

**Comment by nilrodes** [comment]
They have been added to the screen_recording section.
